### ISSUE TITLE
Controller Authorizations Refactor

### ISSUE THREAD

**Issue by stefanjbloom** [turingschool/tracker-crm#42]
After the inclusion of Pundit and policies, we need to figure out what controller action's a user can take vs. what an admin can take.  An admin should have almost complete read/write CRUD functionality, while the user should only have read/write CRUD functionality scoped only to resources that match that user's id.

This refactor will encompass:

- [x] **job_applications_controller.rb** and associated tests (if breaking)
- [x] **contacts_controller.rb** and associated tests (if breaking)
- [x] **companies_controller.rb** and associated tests (if breaking)

Inside each controller action, we need to define what a user can do by using the `authorize` method and, in some cases, the `policy_scope(ClassName)` method.  **UsersController** can be used as a template for these changes.

**Comment by epintozzi** [comment]
Double check for passing tests
