### ISSUE TITLE
Controller Policies

### ISSUE THREAD

**Issue by stefanjbloom** [turingschool/tracker-crm#43]
This connects with issue #42 

Set up Policies for each controller.  Utilize the README.md section **Understanding the [Pundit Gem](https://github.com/varvet/pundit/blob/main/README.md)** for reference.  Policies will enforce what controller actions should be taken based on a user's role.  At the moment, there are only 2 user roles, :admin and :user.

Policies to factor and test:

- [x] **company_policy.rb** and **company_policy_spec.rb**
- [x] **contact_policy.rb** and **contact_policy_spec.rb**
- [x] **job_policy.rb** and **job_policy_spec.rb**

Use the readme and, optionally, for template for polices in **user_policy.rb** and **user_policy_spec.rb**

**Comment by epintozzi** [comment]
Double check for passing tests
